export enum SERVICE_TYPES {
  LOAD_STATE = "LOAD_STATE",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  LOAD_SIGN_PROMPT_STATE = "LOAD_SIGN_PROMPT_STATE",
  SIGN_PROMPT_STATE_CHANGED = "SIGN_PROMPT_STATE_CHANGED",
  GRANT_ACCESS = "GRANT_ACCESS",
  REJECT_ACCESS = "REJECT_ACCESS",
  SELECT_CONNECTION = "SELECT_CONNECTION",
  TOGGLE_HIDDEN_MODE = "TOGGLE_HIDDEN_MODE",
  LOAD_CACHED_ASSETS = "LOAD_CACHED_ASSETS",
  PROCESS_NEW_ASSETS = "PROCESS_NEW_ASSETS",
  GET_LUMEN_QUOTES = "GET_LUMEN_QUOTES",
  CANCEL_LOGIN_POLLING = "CANCEL_LOGIN_POLLING",
}

export enum EXTERNAL_SERVICE_TYPES {
  REQUEST_ACCESS = "REQUEST_ACCESS",
  SIGN = "SIGN",
  // matched by key, so each value must equal its key; SUBMIT_TRANSACTION is the old name
  SUBMIT_TRANSACTION = "SUBMIT_TRANSACTION",
  SIGN_TRANSACTION = "SIGN_TRANSACTION",
  REQUEST_CONNECTION_STATUS = "REQUEST_CONNECTION_STATUS",
}

export enum TX_STATUS {
  pending = "pending",
  signed = "signed",
  rejected = "rejected",
}

export const EXTERNAL_MSG_REQUEST = "LOBSTR_EXTERNAL_MSG_REQUEST";
export const EXTERNAL_MSG_RESPONSE = "LOBSTR_EXTERNAL_MSG_RESPONSE";

export const CONNECTION_KEY = "LOBSTR_CONNECTION_KEY";

declare const DEV_SERVER: string;
const _DEV_SERVER = DEV_SERVER;
export { _DEV_SERVER as DEV_SERVER };

declare const DEV_EXTENSION: string;
const _DEV_EXTENSION = DEV_EXTENSION;
export { _DEV_EXTENSION as DEV_EXTENSION };
